# This file serves as the configurations for the benchmarking experiments, including the basic configuration and the parameters for all attacks and defenses that are going to be tested. You can copy this file and modify it to run your own single attack and defense experiments.
seed: 4 # seed for reproducibility
# basic configuration
epochs: 20 # global epochs
algorithm: FedSGD # algorithm, FedSGD, FedAvg, FedOpt
optimizer: SGD # optimizer for training
momentum: 0.9
weight_decay: 5.0e-4
# lr_scheduler: MultiStepLR # learning rate scheduler
# milestones: [0.6, 0.8] # milestones for learning rate scheduler
num_clients: 50 # number of participating clients
batch_size: 64 # batch_size
learning_rate: 0.01 # clients' local learning rate
model: mlp # model architecture
dataset: RT_IOT2022 # dataset
distribution: iid # data distribution
im_iid_gamma: 0.01 # For class-imbalanced iid, smaller gamma, stronger imbalance, 0.5, 0.6 reference: centered clipping
tail_cls_from: 4 # For class-imbalanced iid, the tail classes start from 4
dirichlet_alpha: 0.5 # For non-iid, smaller alpha, stronger heterogeneity, normally use 0.1, 0.5, 0.9, 1
cache_partition: False # whether to cache the partitioned client indices
gpu_idx: [0] # Indices of GPU
num_workers: 0
record_time: False

# general attack settings
num_adv: 40 # the proportion (float < 1) or number (int>1) of adversaries

attack: LabelFlipping
defense: TrimmedMean

# ! Please follow the format below to specify the attack and defense settings
# ! for attacks, `num_adv` should be specified, and `attack_params` should be specified with the corresponding parameters.
# ! Note that for backdoor attacks, you should specify the backdoor strategy, ['all2one', 'all2all', 'targeted'] and corresponding parameters, `poisoning_ratio` and [`source_label`, `target_label`] for targeted, `target_label` for all2one, nothing for all2all.

attacks:
    - attack: NoAttack

    - attack: Gaussian
      attack_params:
          noise_mean: 0
          noise_std: 1

    - attack: SignFlipping

    - attack: IPM
      attack_params:
          scaling_factor: 0.5

    - attack: ALIE

    - attack: Mimic
      attack_params:
          choice: 0

    - attack: MinMax
      attack_params:
          gamma_init: 10
          stop_threshold: 1.0e-5

    - attack: MinSum
      attack_params:
          gamma_init: 10
          stop_threshold: 1.0e-5

    - attack: FangAttack
      attack_params:
          stop_threshold: 1.0e-5
defenses:
    - defense: Mean
    - defense: SimpleClustering
    - defense: Krum
      defense_params:
          enable_check: False
    - defense: MultiKrum
      defense_params:
          avg_percentage: 0.2
          enable_check: False
    - defense: TrimmedMean
      defense_params:
          beta: 0.1
    - defense: Median
    - defense: Bulyan
      defense_params:
          enable_check: False
    - defense: RFA
      defense_params:
          num_iters: 3
          epsilon: 1.0e-6
    - defense: FLTrust
      defense_params:
          num_sample: 100
    - defense: CenteredClipping
      defense_params:
          norm_threshold: 100
          num_iters: 1
    - defense: DnC
      defense_params:
          subsample_frac: 0.2
          num_iters: 5
          fliter_frac: 1.0
    - defense: Bucketing
      defense_params:
          bucket_size: 2
          selected_aggregator: "Krum"
    - defense: SignGuard
      defense_params:
          lower_bound: 0.1
          upper_bound: 3.0
          selection_fraction: 0.1
          clustering: "MeanShift"
          random_seed: 2
    - defense: LASA
      defense_params:
          norm_bound: 2
          sign_bound: 1
          sparsity: 0.3
    - defense: Auror
      defense_params: # Parameters for defenses
          indicative_threshold: 1.0e-4
          indicative_find_epoch: 10
    - defense: FoolsGold
      defense_params:
          epsilon: 1.0e-5
          topk_ratio: 0.1
    - defense: Bucketing
      defense_params:
          bucket_size: 2
          selected_aggregator: Krum
    - defense: NormClipping # weak differential privacy=norm clipping + differential privacy
      defense_params:
          weakDP: True
          norm_threshold: 3
          noise_mean: 0
          noise_std: 0.002
    - defense: CRFL
      defense_params:
          norm_threshold: 3
          noise_mean: 0
          noise_std: 0.001
    - defense: DeepSight
      defense_params:
          num_seeds: 3
          threshold_factor: 0.01
          num_samples: 20000
          tau: 0.33
          epsilon: 1.0e-6
    - defense: FLAME
      defense_params:
          gamma: 1.2e-5
